### ISSUE TITLE
Warren County: Add ability to scan Land Contracts

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/property_project_ohio#128]
We need a way to record the value of Land Contracts, which it looks like are in the recorder's office as "LC." 

Also, we need a way to record the value of Land Contracts, which it looks like are in the recorder's office as "LC." For example, this property was sold in 2018 for $180,000:

![image](https://user-images.githubusercontent.com/6817579/51948983-73588f00-2409-11e9-8995-dcdb0fdf5ae6.png)

But they are on the books as $137,710: http://www.co.warren.oh.us/property_search/summary.aspx?account_nbr=1111809

A 23.5% increase.

**Comment by ludstuen90** [comment]
@walinchus How would we store land contracts? 

To try and make things easy, I'll present what I think are the two options. 

Option one: 
Store land contract values in the same fields that we currently have (`date_of_mortgage` and `mortgage_amount`).  In this case, we would store whatever option is the most recent. For example, if Family Garúa has a mortgage in 2007 and then a land contract in 2012 on the same property ,we would store the land contract as the mortgage. 

Option two: 
We want to store land contracts in addition to mortgages. This means adding two new database fields, and then we will look to see if the most recent owner has any land contracts on the property. 

My sense is it's option one, no?

**Comment by walinchus** [comment]
Yes I agree option one sounds better. Really both the mortgage and the land contracts are essentially telling us the same thing: What the market values the property at, whereas what it's actually on the books for. I'd say to combine them and change the label to "estimated market value."

**Comment by ludstuen90** [comment]
Sounds great, I will try and make this change when I get home tonight!

**Comment by ludstuen90** [comment]
@walinchus Added code to detect land contracts and changed the admin label. In the example we noted above, our code would return no mort, as the date of sale happened after the LC date. 

I'm starting to think though that might be a problem. It looks like the LC relates to the sale, just that the LC was entered before the DEED was. We're filtering based on the date things are entered into the system. Though it might be a little messier to filter, I wonder if we want to try and filter based on names, instead. 

What do you think?

In any case, to merge in these changes, there's a database change, so be sure to mirgate!

**Comment by ludstuen90** [comment]
Also if rerunning the scraper, remember we have the filter to exlude any properties scanned within the last 7 days, so if we want to start from scratch we will need to remove this filter

**Comment by walinchus** [comment]
Hmm. What if we just ignore all deeds in the filtering process? They tell us about ownership, but not estimated value.

**Comment by walinchus** [comment]
Ah ok. I can comment this out for now. It will pick up the LCs now though, right?

**Comment by ludstuen90** [comment]
Ahhh, ok yes we could do that! Since all we care about is estimated value
and not owner we could very easily just pull whatever most recent mortgage
item or LC there is and go with that

I can try and make that update this afternoon!

**Comment by walinchus** [comment]
Great thanks

**Comment by ludstuen90** [comment]
@walinchus All merged in with this update! It includes another database update, so be sure to migrate the database. Wooo, I think this means we've got our last change for Warren county done! Any questions with this, let me know!
