### ISSUE TITLE
Write script to keep Python script running 

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/property_project_ohio#132]
As a script user, for our own sanity, we don't want to have to keep checking the script to restart if it fails. Write a method to restart the script after any unhandled exception occurs.

**Comment by ludstuen90** [comment]
Code change implemented! This will help create a better experience. 

We can set the script to run infinitely by using the following command: `python infinite.py warren-mort`

 In this case, we'll want to keep track of the scraper's progress on our homepage, so that once the script finishes, we won't keep running.

@walinchus Do you want to give this a try, and if it looks good, close this issue? 

I think this will allow us to not have to worry so much about catching each individual exception that comes up.

**Comment by walinchus** [comment]
This is a good idea. I should have thought of it myself, haha. The script has actually finished running right now. But I will add it in when we look for the LCs.

**Comment by ludstuen90** [comment]
Woo, the script finished!

And all good, no worries - there's a lot of things to think about!
