### ISSUE TITLE
Proxies, different settings per scraper and timing

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/property_project_ohio#150]
- Add in the ability to store different settings per scraper, rather than storing them in all inside the `settings.py` file
- Add in proxies, such that the scraper will send request from proxies, rather than from the same place
- Update variable to send requests at a different speed

**Comment by ludstuen90** [comment]
@walinchus Hey there, good news! I added in proxy information. We can set the proxy on or off by editing the USE_PROXY boolean in `scrapyohio\scrapyohio\settings.py` on line 28. 

If it's set to `True` , the system will send requests using the proxies printed out in `scrapyohio\scrapyohio\proxies.txt`. We can add to this proxy list if it proves not to be enough!

**Comment by ludstuen90** [comment]
Also, I updated the wiki!

**Comment by ludstuen90** [comment]
It turns out, according to scrapy documentation, requests are already passed in at a different speed, so no need to edit this. 

https://doc.scrapy.org/en/latest/topics/settings.html#download-delay

```
This setting is also affected by the RANDOMIZE_DOWNLOAD_DELAY setting 
(which is enabled by default). By default, Scrapy doesn’t wait a fixed amount 
of time between requests, but uses a random interval between 
0.5 * DOWNLOAD_DELAY and 1.5 * DOWNLOAD_DELAY.
```

**Comment by ludstuen90** [comment]
@walinchus  How are we doing on this? Are we good to close this issue? 

It looks like we have a proxy feature to use if needed. 

What we could do before closing the issue: Set the proxy list to be active by default on certain counties. Right now it's an on-off switch, but I would like to see us move more toward per-county settings. 

IE: 
Cuyahoga County: 
- USE_PROXIES: `True`
- IGNORE_ROBOTS: `False`

Another County
- USE_PROXIES: `False`
- IGNORE_ROBOTS: `True`

**Comment by walinchus** [comment]
I think that makes sense. It looks like each county is very different. Or at least, not a whole lot of consistency.
