### ISSUE TITLE
Identify property class and store

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/property_project_ohio#58]
What is `property_class`? Where is it stored? How can we scrape it?

**Comment by ludstuen90** [comment]
property_class | varchar | -- 
"we might just limit this to commercial properties"

**Comment by walinchus** [comment]
Well we don't want to find only commercial properties. For the land bank stories, knowing which ones are residential and delinquent will be key. But I do think they probably overlap a bit. Property class is actually probably the more important one, though I think actually getting them both would be helpful.

**Comment by ludstuen90** [comment]
@walinchus Makes sense! What are the property classes we'd be looking for? In my research, I've found Class A, B, C and D properties, but that seems to refer more to the quality of a property VS the type of property it is (industrial vs residential) — I think I'm missing something! 

Is there any definitive source on property class? I don't seem to find it in Warren County's property system

**Comment by ludstuen90** [comment]
Will store here classifications like  `APARTMENTS 40 OR MORE UNITS (ELEVATOR)` rather than `C`

**Comment by ludstuen90** [comment]
As per meeting, we will want to store both types of property class, when possible. Making a MR to add this database field.

**Comment by ludstuen90** [comment]
Closing this issue, as this information is not available in Warren County.
