### ISSUE TITLE
Warren County: R/M 

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/property_project_ohio#97]
@walinchus will confirm that we want to catch R/M in Warren County mortgage items. 

If so, code this in to catch these on mortgage search. 

- [x]  Updated code
- [ ]  Verify change works
- [ ]  Update tests to account for this

**Comment by walinchus** [comment]
Yes it looks like those are also mortgages

**Comment by ludstuen90** [comment]
Updated the code, just need to find a R/M record to simulate testing.

**Comment by ludstuen90** [comment]
https://oh3laredo.fidlar.com/OHWarren/AvaWeb/#!/searchResults?Parcel=1833428001 
http://www.co.warren.oh.us/property_search/summary.aspx?account_nbr=3907742 


save this property to look at for later, appear to be several mortgages

**Comment by ludstuen90** [comment]
Closing this, as we won't take R/M properties after all.
