### ISSUE TITLE
Property Class: Add scraping property 

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/property_project_ohio#98]
Property Class: Add new field to scrape the Property Class of ABCD if possible.

**Comment by walinchus** [comment]
Ok done. Looks successful: 
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, propertyrecords, sessions
Running migrations:
  Applying propertyrecords.0009_property_property_rating... OK

**Comment by ludstuen90** [comment]
Awesome, thanks for doing that!
